"""Scene-level Kokoro synthesis. Input/output are local JSON/files, never shell text."""
import hashlib
import shutil
import json
import os
import sys
import time
from pathlib import Path

os.environ.setdefault("HF_HUB_DISABLE_TELEMETRY", "1")
import numpy as np
import soundfile as sf
import torch
from kokoro import KPipeline

torch.set_num_threads(int(os.environ.get("TTS_THREADS", "2")))
started = time.monotonic()
project = json.loads(Path(sys.argv[1]).read_text(encoding="utf-8"))
destination = Path(sys.argv[2]).resolve()
destination.mkdir(parents=True, exist_ok=True)
cache = Path(os.environ.get("TTS_CACHE_DIR", "runs/tts-cache")).resolve()
cache.mkdir(parents=True, exist_ok=True)
# Bound the cache. Only files generated by this cache are eligible for eviction.
records = sorted(cache.glob("*.json"), key=lambda p: p.stat().st_mtime, reverse=True)
for record in records[500:]:
    if len(record.stem) == 64 and all(c in "0123456789abcdef" for c in record.stem):
        record.with_suffix(".wav").unlink(missing_ok=True)
        record.unlink(missing_ok=True)
pipeline = None
cache_hits = 0
results = []
for index, scene in enumerate(project["scenes"]):
    name = f"scene-{index}.wav"
    key = hashlib.sha256(json.dumps({"model": "Kokoro-82M-cache-v1", "voice": project["voice"], "speed": project["speed"], "text": scene["narration"]}, sort_keys=True).encode()).hexdigest()
    meta, wav = cache / f"{key}.json", cache / f"{key}.wav"
    if meta.exists() and wav.exists():
        try:
            saved = json.loads(meta.read_text(encoding="utf-8"))
            if saved.get("sha256") == hashlib.sha256(wav.read_bytes()).hexdigest():
                shutil.copyfile(wav, destination / name)
                results.append({"file": name, "seconds": saved["seconds"], "words": saved["words"]})
                cache_hits += 1
                continue
        except (OSError, ValueError, KeyError):
            pass  # A missing/partial cache record is a miss, never a failed lesson.
    if pipeline is None:
        pipeline = KPipeline(lang_code="a", repo_id="hexgrad/Kokoro-82M", device="cpu")
    pieces, words, offset = [], [], 0.0
    for result in pipeline(scene["narration"], voice=project["voice"], speed=project["speed"]):
        audio = result.audio.numpy()
        pieces.append(audio)
        for token in result.tokens or []:
            if token.start_ts is not None and token.end_ts is not None:
                words.append({"text": token.text, "start": offset + token.start_ts, "end": offset + token.end_ts})
        offset += len(audio) / 24000
    audio = np.concatenate(pieces)
    name = f"scene-{index}.wav"
    sf.write(destination / name, audio, 24000, subtype="PCM_16")
    result = {"file": name, "seconds": len(audio) / 24000, "words": words}
    results.append(result)
    temporary_wav = cache / f"{key}.{os.getpid()}.wav.tmp"
    temporary_meta = cache / f"{key}.{os.getpid()}.json.tmp"
    shutil.copyfile(destination / name, temporary_wav)
    temporary_meta.write_text(json.dumps({**result, "sha256": hashlib.sha256(temporary_wav.read_bytes()).hexdigest()}), encoding="utf-8")
    os.replace(temporary_wav, wav)
    os.replace(temporary_meta, meta)
peak = None
if sys.platform != "win32":
    import resource
    peak = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss / 1024
report = {"scenes": results, "cacheHits": cache_hits, "synthesisSeconds": time.monotonic() - started, "peakRssMb": peak, "sampleRate": 24000, "model": "hexgrad/Kokoro-82M", "voice": project["voice"], "timingMethod": "Kokoro predicted token durations; not forced alignment"}
(destination / "speech.json").write_text(json.dumps(report), encoding="utf-8")
print(json.dumps({"event": "speech_completed", "seconds": report["synthesisSeconds"], "audioSeconds": sum(x["seconds"] for x in results)}))
