import type { TRANSFORM_KINDS, VisualKind } from "../../packages/contracts/visual";

/** Renderer vocabulary, not lesson evidence. Keep aligned with MechanismGlyph
 * and EverydayGlyph; descriptions deliberately state what the SVG draws. */
export const glyphCatalog = {
  geometry: "Except label, every glyph uses a fixed 100x100 drawing fitted uniformly into its viewport: side=min(w*12.8,h*7.2) pixels. w/h never stretch its silhouette. A box at w=32,h=6 fits into a 43.2px square, NOT a long contact/bar. Leave space for the actual silhouette and separate text; labels do not alter shapes. Use relations for lines, arrows and connections, not relabeled object glyphs.",
  parameters: "count=1..16, default4, affects only atom, molecule, lattice, token, grid and layers as described below; all other kinds ignore count. values affects only bars/pie. Variant affects geometry only where listed; on stateful glyphs closed/negative also initializes state0 (otherwise1). First transform instead initializes the opposite endpoint: value0 starts1, any other value starts0. Transform interpolates only the listed states, never identity. Kinds absent from transform have no supported transform action.",
  glyphs: {
    sun: "Disk with 12 radial rays; not a point light or photon.",
    "solar-panel": "Tilted blue-capable panel with a fixed 4x4 cell grid, thick lower edge and two support feet; exterior only, no junction cutaway or variable cell count.",
    photon: "Right-pointing wavy arrow with three short rays; symbolic packet, not a dot. Rotate the whole glyph for another heading.",
    electron: "Colored disk with a permanent minus sign and white shine; not an atom or unsigned particle.",
    atom: "Three fixed elliptical orbits, three colored nucleus disks, plus count small blue orbit dots. Schematic only: count does NOT set protons/nucleons or chemical identity.",
    molecule: "count colored balls connected sequentially by thick bonds; two form a pair, larger groups sit around a polygon with no closing bond. Generic open schematic chain, not a named compound's geometry.",
    lattice: "Exactly count round nodes with horizontal/vertical bonds, row-major in n=max(2,ceil(sqrt(count))) columns. Local centers run from(15,15) with spacing70/(n-1), radius8; only occupied rows/columns exist. Counts4/9/16 fill node bounds7..93 on both axes; count2 is only a top row, not a filled square. No solid material background. Legacy positive adds two unsigned blue dots, NOT positive holes; do not request that variant/transform for new direction.",
    battery: "Physical horizontal battery outline with terminal, minus/plus markings and segmented color fill; vertical rotates it90deg. Energy-storage object, not a generic voltage/potential label or field symbol.",
    bulb: "Lightbulb with filament, gray screw base and short surrounding light rays.",
    house: "Pitched-roof house with chimney, door and windows; no interior rooms/circuit.",
    plant: "Leafy stem above a ground line; not a seed or roots. Growth retains the same leaves.",
    root: "Branched root below a soil line with a short stem above it; no leaves or moving fluid.",
    flower: "Five-petal flower with yellow center, green leaves and stem; fixed petal count.",
    seed: "Single bean-shaped seed with seam and highlight; no sprout or opening state.",
    water: "One large teardrop with white highlight; no pool, molecule or fill level.",
    beaker: "Narrow-neck conical laboratory flask with volume ticks and colored liquid; not a straight-sided glass.",
    cloud: "Single rounded cloud outline with colored fill; no rain or vapor particles.",
    gear: "Toothed wheel with circular center hole; fixed teeth, count ignored. Rotate moves the whole wheel.",
    turbine: "Three-blade wind turbine on a mast; rotate moves mast AND blades, not an independent rotor.",
    magnet: "U-shaped horseshoe with red/blue end caps; no N/S letters, charge signs or field lines. horizontal rotates the whole U90deg.",
    speaker: "Rectangular two-cone loudspeaker with sound arcs at its right.",
    book: "Symmetric open book with center spine and page lines; opening narrows/widens both page halves, no page-turn.",
    document: "Single sheet with folded corner, a colored block and fixed text-like lines; cannot display arbitrary document content.",
    person: "Head-and-shoulders portrait with face, hair and shirt; not a walking figure or gesture rig.",
    brain: "Two-lobed brain outline with folds and central division; no neural network nodes.",
    chip: "Square integrated circuit with pins on four sides and a smaller central square; not a database.",
    computer: "Desktop monitor on a stand with fixed code brackets on screen; no keyboard or arbitrary screen content.",
    database: "Cylinder with three stacked storage bands; not a physical chip or list of rows.",
    magnifier: "Round white lens with colored rim and diagonal handle; does not magnify other entities.",
    clock: "Round analog clock with four ticks and two hands; no numerals or digital time.",
    shield: "Shield outline containing a permanent check mark; not a blank shield.",
    container: "Open bucket/cup with elliptical rim, tapered sides and optional liquid fill; not a shipping box or sealed chamber.",
    token: "Exactly count double-ring disks arranged in centered rows; generic tokens/coins, no symbols or values inside.",
    filter: "Mesh-topped funnel with narrow outlet; filtering is represented by separate entity/relation actions, not internal particle sorting.",
    memory: "Three offset document cards with lines and bookmark; not a RAM circuit or brain.",
    pipe: "Thick stepped plumbing pipe with two elbows and end flanges; colored internal channel. vertical rotates90deg. Not a wire, straight connector or circuit return line.",
    thermometer: "Bulb-and-stem thermometer with four ticks and colored column; no numeric scale.",
    heat: "Three upward wavy arrows; fixed direction and count, no temperature readout.",
    wave: "Two-cycle sinusoid over a straight baseline; vertical rotates90deg. No traveling phase or frequency change.",
    globe: "Tilted latitude/longitude globe on a stand; no land outlines, countries or globe-only spin.",
    scale: "Physical two-pan balance with beam and support; not a ruler, zoom factor or number axis.",
    valve: "Plumbing gate valve with handwheel above a horizontal pipe; stem/gate lift and blue passage appear when open.",
    check: "Single thick check mark.",
    cross: "Single thick X mark; not a plus sign.",
    bars: "Vertical bars on bare L-shaped axes; values set heights relative to max(values,1) and print numbers above bars. No category labels/units; count ignored. Supply supported values.",
    pie: "Circular colored sectors in values ratios; no numeric/category labels. Supply supported values; count ignored.",
    grid: "Exactly count small square tiles in up to4 columns, row-major; missing final-row cells stay absent. Tiles fill discretely with state.",
    layers: "Exactly count overlapping diamond-shaped slabs, drawn bottom to top; fixed isometric stack, NOT field arrows, parallel lines or a flat rectangular contact. No separation state.",
    circle: "Filled circle, diameter76% of fitted square; positive draws+, negative draws-. Otherwise unsigned. Variants do not create separate particles.",
    box: "Rounded rectangle of fixed local width82,height72 inside fitted square; cannot stretch into a long thin slab/contact/wire. No opening or internal subdivision.",
    label: "Only the entity.label text, uppercase hand lettering centered at x/y; no icon or background, no mathematical typesetting.",
  } satisfies Record<VisualKind, string>,
  transform: {
    battery: "0 empty color fill ->1 full segmented fill; terminal/signs remain.",
    bulb: "0 unlit white bulb/no rays ->1 colored bulb/visible rays.",
    plant: "0 same plant at35% size ->1 full size, rooted at its base; not germination.",
    flower: "0 petals at55% size ->1 full-size petals; stem/leaves unchanged.",
    speaker: "0 hidden sound arcs ->1 visible arcs; cones do not move.",
    book: "0 narrow page spread ->1 wide open spread; not fully shut or a page-turn.",
    clock: "0 one hand points up ->1 that hand rotates300deg; other hand stays fixed.",
    container: "0 empty ->1 raised colored liquid level; body/rim fixed.",
    pipe: "0 empty internal channel ->1 thick colored channel; pipe shape fixed.",
    thermometer: "0 low colored stem ->1 raised column; bulb stays filled.",
    scale: "0 left pan higher/right lower ->1 level beam; never tips the other way.",
    valve: "0 gate lowered/closed ->1 lifted/open with blue flow passage; wheel does not turn independently.",
    beaker: "0 no liquid ->1 raised colored liquid level; flask fixed.",
    wave: "0 amplitude35% ->1 full amplitude; never zero amplitude or changing wavelength.",
    bars: "0 near-zero bar height ->1 values-scaled height; printed numbers stay the original values.",
    pie: "0 no colored sweep ->1 complete ratio chart; intermediate sweep is not a new dataset.",
    grid: "0 white tiles ->1 all colored; intermediate state fills leading row-major tiles in steps.",
  } satisfies Record<(typeof TRANSFORM_KINDS)[number], string>,
};
